### ISSUE TITLE
navの色を修正してください。

### ISSUE THREAD

**Issue by ahnjy-f** [ahnjy-f/fresh20_todo#2]
nav.ejsのファイルで、
バックグラウンドの色を#008b8bにして欲しいです。

**Comment by dlehddus1285** [comment]
ソンさんが編集します！

**Comment by bjson05** [comment]
> nav.ejsのファイルで、
> バックグラウンドの色を#008b8bにして欲しいです。

**Comment by ahnjy-f** [comment]
> nav.ejsのファイルで、
> バックグラウンドの色を#008b8bにして欲しいです。

まだ出来ていません。

**Comment by bjson05** [comment]
私が修正します。
